### ISSUE TITLE
Add line break setting

### ISSUE THREAD

**Issue by denovodavid** [NeilClarkAssociates/SVGGraph#1]

**Comment by smeagolem** [comment]
Closed by https://github.com/NeilClarkAssociates/SVGGraph/commit/e900aa6829b52076dbf2e8ceb9a740affa9b2b40

**Comment by denovodavid** [comment]
Closed by https://github.com/NeilClarkAssociates/SVGGraph/commit/e900aa6829b52076dbf2e8ceb9a740affa9b2b40
